# Generated by Django 5.2.6 on 2025-09-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100, verbose_name='Nome do Solicitante')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='Data da Requisição')),
                ('request_time', models.TimeField(auto_now_add=True, verbose_name='Hora da Requisição')),
                ('department', models.CharField(max_length=100, verbose_name='Setor')),
                ('maintenance_type', models.CharField(choices=[('eletrica', 'Elétrica'), ('mecanica', 'Mecânica'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Manutenção')),
                ('equipment_status', models.CharField(choices=[('funcionando', 'Funcionando'), ('alerta', 'Alerta'), ('inoperante', 'Inoperante')], max_length=20, verbose_name='Status do Equipamento')),
                ('equipment_location_press', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prensa')),
                ('equipment_location_press_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº da Prensa')),
                ('equipment_location_thread', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rosca')),
                ('equipment_location_thread_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº da Rosca')),
                ('equipment_location_other', models.CharField(blank=True, max_length=100, null=True, verbose_name='Outros (Localização)')),
                ('equipment_location_other_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº (Outros)')),
                ('problem_description', models.TextField(verbose_name='O que está ocorrendo?')),
                ('maintenance_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº da Manutenção')),
                ('execution_date', models.DateField(blank=True, null=True, verbose_name='Data de Execução')),
                ('executor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Executor')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora Início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora Término')),
                ('total_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tempo Total')),
                ('execution_description', models.TextField(blank=True, null=True, verbose_name='Descrição da Manutenção Executada')),
            ],
            options={
                'verbose_name': 'Requisição de Manutenção',
                'verbose_name_plural': 'Requisições de Manutenção',
            },
        ),
    ]
