# Generated by Django 5.2.6 on 2025-09-25 14:19

from django.db import migrations
from django.contrib.auth import get_user_model

def create_test_users(apps, schema_editor):
    User = get_user_model()
    password = 'password123'

    # Admin User (Superuser)
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser('admin', 'admin@example.com', password)

    # Operator User
    if not User.objects.filter(username='operator').exists():
        operator_user = User.objects.create_user('operator', 'operator@example.com', password)
        operator_user.role = 'operator'
        operator_user.save()

    # Maintenance User
    if not User.objects.filter(username='maintenance').exists():
        maintenance_user = User.objects.create_user('maintenance', 'maintenance@example.com', password)
        maintenance_user.role = 'maintenance'
        maintenance_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_users),
    ]
